function cafvaResult = CAFVA_glpk(model,varargin)
% CAFBA_FVA_glpk
% Performs reaction-wise flux variability analysis under the exact CAFBA
% LP generated by CAFBA_buildLP.
%
% For each target reaction j, CAFVA solves:
%
%   min v_j
%   max v_j
%
% while retaining a selected percentage of the optimum of the original
% CAFBA objective.
%
% USAGE
%
%   result = CAFVA_glpk(model)
%
%   result = CAFVA_glpk(model, ...
%       'rxnNameList',{'PDH','PPCK','PPS'}, ...
%       'constraintSense','U', ...
%       'optPercentage',100, ...
%       'osenseStr','max', ...
%       'relativeTolerance',1e-6, ...
%       'absoluteTolerance',1e-8, ...
%       'verbose',0, ...
%       'printLevel',2);
%
% OPTIONAL INPUTS
%
%   'rxnNameList'
%       Reaction IDs or numeric reaction indices. Default: model.rxns
%
%   'constraintSense'
%       CAFBA allocation constraint sense passed to CAFBA_buildLP.
%       Default: 'U'
%
%   'optPercentage'
%       Percentage of the original optimum retained during CAFVA.
%       Default: 100
%
%   'osenseStr'
%       Original objective sense: 'max' or 'min'. Default: 'max'
%
%   'relativeTolerance'
%       Relative tolerance for the original objective constraint.
%       Default: 1e-6
%
%   'absoluteTolerance'
%       Absolute tolerance for the original objective constraint.
%       Default: 1e-8
%
%   'verbose'
%       GLPK message level. Default: 0
%
%   'printLevel'
%       0: silent
%       1: progress
%       2: reaction-wise values
%       Default: 0
%
% OUTPUT
%
%   cafvaResult.minimumFlux
%   cafvaResult.maximumFlux
%   cafvaResult.range
%   cafvaResult.Vmin
%   cafvaResult.Vmax
%   cafvaResult.originalNetFlux
%   cafvaResult.optimalObjective
%
% NOTE
%
% This is ordinary LP-based CAFVA. It does not impose loopless MILP
% constraints.

% -------------------------------------------------------------------------
% Defaults
% -------------------------------------------------------------------------

rxnNameList = model.rxns;
constraintSense = 'U';
optPercentage = 100;
osenseStr = 'max';
relativeTolerance = 1e-6;
absoluteTolerance = 1e-8;
verbose = 0;
printLevel = 0;

% -------------------------------------------------------------------------
% Parse inputs
% -------------------------------------------------------------------------

if mod(length(varargin),2) ~= 0
    error('Optional arguments must be supplied as name-value pairs.');
end

for k = 1:2:length(varargin)
    switch lower(varargin{k})
        case 'rxnnamelist'
            rxnNameList = varargin{k+1};
        case 'constraintsense'
            constraintSense = varargin{k+1};
        case 'optpercentage'
            optPercentage = varargin{k+1};
        case 'osensestr'
            osenseStr = lower(varargin{k+1});
        case 'relativetolerance'
            relativeTolerance = varargin{k+1};
        case 'absolutetolerance'
            absoluteTolerance = varargin{k+1};
        case 'verbose'
            verbose = varargin{k+1};
        case 'printlevel'
            printLevel = varargin{k+1};
        otherwise
            error('Unknown optional argument: %s',varargin{k});
    end
end

if ~isscalar(optPercentage) || optPercentage < 0 || optPercentage > 100
    error('optPercentage must be between 0 and 100.');
end

if ~(strcmp(osenseStr,'max') || strcmp(osenseStr,'min'))
    error('osenseStr must be ''max'' or ''min''.');
end

% -------------------------------------------------------------------------
% Resolve target reactions
% -------------------------------------------------------------------------

nRxns = length(model.rxns);

if ischar(rxnNameList)
    rxnNameList = {rxnNameList};
end

if isnumeric(rxnNameList)

    targetIndices = rxnNameList(:);

    if any(targetIndices < 1) || any(targetIndices > nRxns) || ...
            any(targetIndices ~= round(targetIndices))
        error('Numeric reaction indices are invalid.');
    end

    targetRxnIDs = model.rxns(targetIndices);

elseif iscell(rxnNameList)

    targetRxnIDs = rxnNameList(:);
    targetIndices = zeros(length(targetRxnIDs),1);

    for k = 1:length(targetRxnIDs)

        index = find(strcmp(model.rxns,targetRxnIDs{k}));

        if isempty(index)
            error('Reaction not found: %s',targetRxnIDs{k});
        elseif length(index) > 1
            error('Reaction ID is not unique: %s',targetRxnIDs{k});
        end

        targetIndices(k) = index;
    end

else
    error('rxnNameList must contain reaction IDs or numeric indices.');
end

nTargets = length(targetIndices);

% -------------------------------------------------------------------------
% Build the same CAFBA LP used for ordinary CAFBA optimization
% -------------------------------------------------------------------------

[baseLP,varMap,buildInfo] = CAFBA_buildLP( ...
    model, ...
    'optSense',osenseStr, ...
    'optMode','flux', ...
    'constraintSense',constraintSense, ...
    'verbose',verbose);

% -------------------------------------------------------------------------
% Solve original CAFBA objective
% -------------------------------------------------------------------------

[xOptimal,~,statusOptimal,extraOptimal] = glpk( ...
    baseLP.c,baseLP.A,baseLP.b,baseLP.lb,baseLP.ub, ...
    baseLP.ctype,baseLP.vartype,baseLP.sense,baseLP.param);

% In the GLPK interface used here, status = 5 means that an
% optimal solution was found.
if ~isGLPKOptimal(statusOptimal,extraOptimal)
    error(['Initial CAFBA problem was not solved to optimality. ', ...
        'GLPK status = %d.'],statusOptimal);
end

optimalObjective = baseLP.c(:)' * xOptimal;
originalNetFlux = varMap.T * xOptimal;

% -------------------------------------------------------------------------
% Add original-objective threshold
% -------------------------------------------------------------------------

objectiveTolerance = max( ...
    absoluteTolerance, ...
    relativeTolerance * abs(optimalObjective));

fraction = optPercentage / 100;

if strcmp(osenseStr,'max')
    objectiveThreshold = optimalObjective * fraction - objectiveTolerance;
    objectiveConstraintType = 'L';  % c*x >= threshold
else
    % For a minimization objective, percentages below 100 are interpreted
    % as allowing a proportional increase above the optimum.
    if fraction == 0
        error(['optPercentage=0 is not meaningful for a minimization ', ...
            'objective.']);
    end

    objectiveThreshold = optimalObjective / fraction + objectiveTolerance;
    objectiveConstraintType = 'U';  % c*x <= threshold
end

fvaLP = baseLP;
fvaLP.A(end+1,:) = baseLP.c(:)';
fvaLP.b(end+1,1) = objectiveThreshold;
fvaLP.ctype(end+1,1) = objectiveConstraintType;

% -------------------------------------------------------------------------
% Allocate outputs
% -------------------------------------------------------------------------

minimumFlux = nan(nTargets,1);
maximumFlux = nan(nTargets,1);
minimumStatus = nan(nTargets,1);
maximumStatus = nan(nTargets,1);

Vmin = nan(nRxns,nTargets);
Vmax = nan(nRxns,nTargets);

if printLevel > 1
    fprintf('%5s  %-24s  %14s  %14s\n', ...
        'No.','Reaction','Minimum','Maximum');
end

% -------------------------------------------------------------------------
% Double LP for each reaction
% -------------------------------------------------------------------------

for k = 1:nTargets

    r = targetIndices(k);
    % GLPK in this MATLAB installation requires a full objective vector.
    % varMap.T is sparse, so transpose alone returns a sparse vector.
    % Passing that sparse vector can make GLPK behave as if the objective
    % were zero, causing the minimum and maximum solutions to collapse.
    targetObjective = full(varMap.T(r,:)');

    % Minimum
    LPmin = fvaLP;
    LPmin.c = targetObjective;
    LPmin.sense = 1;

    [xMin,~,statusMin,extraMin] = glpk( ...
        LPmin.c,LPmin.A,LPmin.b,LPmin.lb,LPmin.ub, ...
        LPmin.ctype,LPmin.vartype,LPmin.sense,LPmin.param);

    minimumStatus(k) = statusMin;

    if isGLPKOptimal(statusMin,extraMin)

        primaryValueMin = baseLP.c(:)' * xMin;

        if strcmp(osenseStr,'max') && ...
                primaryValueMin < objectiveThreshold - objectiveTolerance
            error(['Minimum solution for %s violates the retained ', ...
                'CAFBA objective threshold.'],targetRxnIDs{k});
        elseif strcmp(osenseStr,'min') && ...
                primaryValueMin > objectiveThreshold + objectiveTolerance
            error(['Minimum solution for %s violates the retained ', ...
                'CAFBA objective threshold.'],targetRxnIDs{k});
        end

        vNetMin = varMap.T * xMin;
        minimumFlux(k) = vNetMin(r);
        Vmin(:,k) = vNetMin;
    end

    % Maximum
    LPmax = fvaLP;
    LPmax.c = targetObjective;
    LPmax.sense = -1;

    [xMax,~,statusMax,extraMax] = glpk( ...
        LPmax.c,LPmax.A,LPmax.b,LPmax.lb,LPmax.ub, ...
        LPmax.ctype,LPmax.vartype,LPmax.sense,LPmax.param);

    maximumStatus(k) = statusMax;

    if isGLPKOptimal(statusMax,extraMax)

        primaryValueMax = baseLP.c(:)' * xMax;

        if strcmp(osenseStr,'max') && ...
                primaryValueMax < objectiveThreshold - objectiveTolerance
            error(['Maximum solution for %s violates the retained ', ...
                'CAFBA objective threshold.'],targetRxnIDs{k});
        elseif strcmp(osenseStr,'min') && ...
                primaryValueMax > objectiveThreshold + objectiveTolerance
            error(['Maximum solution for %s violates the retained ', ...
                'CAFBA objective threshold.'],targetRxnIDs{k});
        end

        vNetMax = varMap.T * xMax;
        maximumFlux(k) = vNetMax(r);
        Vmax(:,k) = vNetMax;
    end

    zeroTolerance = max(absoluteTolerance,1e-10);

    if ~isnan(minimumFlux(k)) && abs(minimumFlux(k)) < zeroTolerance
        minimumFlux(k) = 0;
    end

    if ~isnan(maximumFlux(k)) && abs(maximumFlux(k)) < zeroTolerance
        maximumFlux(k) = 0;
    end

    if printLevel == 1
        fprintf('CAFVA: %d of %d reactions completed.\n',k,nTargets);
    elseif printLevel > 1
        fprintf('%5d  %-24s  %14.6g  %14.6g\n', ...
            k,targetRxnIDs{k},minimumFlux(k),maximumFlux(k));
    end
end

% -------------------------------------------------------------------------
% Verify that the original optimal flux lies inside every CAFBA-FVA range
% -------------------------------------------------------------------------

originalTargetFlux = originalNetFlux(targetIndices);

rangeTolerance = max( ...
    absoluteTolerance * ones(nTargets,1), ...
    relativeTolerance * max(ones(nTargets,1),abs(originalTargetFlux)));

invalidLower = originalTargetFlux < minimumFlux - rangeTolerance;
invalidUpper = originalTargetFlux > maximumFlux + rangeTolerance;
invalidRange = invalidLower | invalidUpper;

if any(invalidRange)

    bad = find(invalidRange);

    for j = 1:length(bad)
        q = bad(j);

        fprintf(2, ...
            ['Invalid CAFBA-FVA interval for %s: original = %.12g, ', ...
            'minimum = %.12g, maximum = %.12g\n'], ...
            targetRxnIDs{q},originalTargetFlux(q), ...
            minimumFlux(q),maximumFlux(q));
    end

    error(['CAFBA-FVA consistency check failed because the original ', ...
        'optimal solution lies outside at least one calculated interval.']);
end

% -------------------------------------------------------------------------
% Output
% -------------------------------------------------------------------------

cafvaResult.rxnIDs = targetRxnIDs;
cafvaResult.rxnIndices = targetIndices;

cafvaResult.minimumFlux = minimumFlux;
cafvaResult.maximumFlux = maximumFlux;
cafvaResult.range = maximumFlux - minimumFlux;

cafvaResult.Vmin = Vmin;
cafvaResult.Vmax = Vmax;

cafvaResult.minimumStatus = minimumStatus;
cafvaResult.maximumStatus = maximumStatus;

cafvaResult.optimalObjective = optimalObjective;
cafvaResult.optPercentage = optPercentage;
cafvaResult.objectiveTolerance = objectiveTolerance;
cafvaResult.objectiveThreshold = objectiveThreshold;

cafvaResult.originalNetFlux = originalNetFlux;
cafvaResult.originalTargetFlux = originalTargetFlux;

cafvaResult.constraintSense = constraintSense;
cafvaResult.osenseStr = osenseStr;
cafvaResult.buildInfo = buildInfo;

end

function tf = isGLPKOptimal(statusValue,extraValue)
% isGLPKOptimal
%
% Return true when GLPK reports an optimal solution.
%
% In the GLPK version used for this project, the third output of glpk()
% is the solution status and:
%
%     statusValue = 5
%
% means that an optimal solution was found.
%
% The fallback checks extraValue.status for compatibility with interfaces
% that store the solution status in the fourth output.

tf = false;

if isequal(statusValue,5)
    tf = true;
    return;
end

if isstruct(extraValue) && isfield(extraValue,'status')
    tf = isequal(extraValue.status,5);
end

end

